### ISSUE TITLE
Documentation overview/tracking issue.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#199]
EDITED. 11 December.

For the following documentation I am using a mix of direct advice from Joe, the old documentation and how I understand things along the way. These are in various degree of completion. 

- [ ] Events (Manage Events) https://docs.joedolson.com/my-calendar/my-calendar-manage-events/
   - [ ] Add Event https://docs.joedolson.com/my-calendar/my-calendar-add-event/
   - [ ] Add Event - Add Copy https://docs.joedolson.com/my-calendar/my-calendar-add-event-add-copy/
   - [ ] Add Event - Repetition Pattern https://docs.joedolson.com/my-calendar/my-calendar-add-event-repetition-pattern/
   - [ ] My Events https://docs.joedolson.com/my-calendar/my-calendar-events-my-events/
   - [ ] Event Groups https://docs.joedolson.com/my-calendar/my-calendar-event-groups/
   - [ ] Frontend Event Views https://docs.joedolson.com/my-calendar/my-calendar-frontend-event-views/
- [ ] Add New Location https://docs.joedolson.com/my-calendar/my-calendar-location-add-new-location/ (Needs work)
- [ ] Locations https://docs.joedolson.com/my-calendar/locations/
   - [ ] Edit Location 
- [ ] Categories https://docs.joedolson.com/my-calendar/my-calendar-categories/
    - [ ] Category Icon https://docs.joedolson.com/my-calendar/my-calendar-category-icons/
- [ ] Design
   - [ ] Style Editor https://docs.joedolson.com/my-calendar/my-calendar-design-style-editor/
   - [ ] Templates https://docs.joedolson.com/my-calendar/my-calendar-design-templates/ 
      - [ ] Template Tag Index  https://docs.joedolson.com/my-calendar/my-calendar-template-tag-index/
   - [ ] Scripts https://docs.joedolson.com/my-calendar/my-calendar-design-scripts/
- [ ] Settings 
   - [ ] General https://docs.joedolson.com/my-calendar/my-calendar-general-settings/
   - [ ] Text https://docs.joedolson.com/my-calendar/my-calendar-text-settings/
   - [ ] Output https://docs.joedolson.com/my-calendar/my-calendar-output-settings/
   - [ ] Input https://docs.joedolson.com/my-calendar/my-calendar-input-settings/
   - [ ] Permissions https://docs.joedolson.com/my-calendar/my-calendar-permissions-settings/
   - [ ] Notifications https://docs.joedolson.com/my-calendar/my-calendar-notifications-settings/
- [ ] Shortcodes https://docs.joedolson.com/my-calendar/my-calendar-shortcodes/
- [ ] Help
   - [ ] Getting Started / Quick Start Guide https://docs.joedolson.com/my-calendar/my-calendar-quick-start-guide-getting-started/
   - [ ] Custom Files https://docs.joedolson.com/my-calendar/my-calendar-help-custom-files/
   - [ ] Privacy https://docs.joedolson.com/my-calendar/my-calendar-help-privacy/
   - [ ] Get Support https://docs.joedolson.com/my-calendar/my-calendar-help-get-support/
----
  - [ ] Block Widgets https://docs.joedolson.com/my-calendar/my-calendar-widgets/

Associated:
Overview of screens that use the icon ? help popups to give additional information.
https://github.com/joedolson/my-calendar/issues/301

**Comment by joedolson** [comment]
Docs issue: https://docs.joedolson.com/my-calendar/my-calendar-display-settings/

Screenshots for the default views need to be updated. Two issues:

1) Re-take them using the latest version of the twenty-twenty-one stylesheet.
2) Make sure they're using the default settings for a new installation. These are currently showing the settings for an *updated* installation.
3) For the mini calendar, take a screenshot of the popup; not a screenshot of the grid.

**Comment by paaljoachim** [comment]
I have updated the screenshots.
1. Done.
2. I downloaded the newest version of My Calendar and took a new screenshot. I assume this should now be correct.
3. This one I do not understand.

**Comment by joedolson** [comment]
For the second point, I'm referring to the settings screenshots for Display output & the screenshots that go with them. e.g.

![image](https://user-images.githubusercontent.com/1686451/145688581-50b67b2d-8588-4e2d-98dd-ddf58d62f8f2.png)

That image doesn't show the default settings for a fresh installation of My Calendar. (Fresh meaning: all previous settings deleted.)

For the 3rd point, I mean this screenshot: 

![image](https://user-images.githubusercontent.com/1686451/145688636-fb7b0ad6-54e0-4500-aaaa-c18cddf30670.png)

That screenshot is placed for the heading "Mini Calendar Popup" but does not contain the popup.

**Comment by paaljoachim** [comment]
2. I assume totally removing the plugin would on each fresh install show the default of Single Event, Main View and Mini Calendar Popup. It seems that is not the case. Making it tricky to get back the default of each of these areas.
I noticed an error which I added here: https://github.com/joedolson/my-calendar/issues/407

3. Updated the current Mini Calendar screenshot and added in the mini calendar popup screenshot:
https://docs.joedolson.com/my-calendar/my-calendar-display-settings/

**Comment by joedolson** [comment]
2. It should; looking to see why it isn't.

**Comment by joedolson** [comment]
Those options were missing from the uninstall routine. Fixed.

**Comment by paaljoachim** [comment]
### In progress

I am going through the My Calendar v3.2.0 pdf guide again

Overview - screenshots are added into various doc pages.

The Basics/ 1. Installation - How to install a plugin is not added to the My Calendar doc pages. Information about fully removing the plugin is added to My Calendar -> Settings -> General doc.

2.Configuration.

2.a. My Calendar -> Settings -> General 
Define Your Main Calendar Page - [x] 
Admin Event Sort Order - [x]
Use Pretty Permalinks For Events - [x]
Fetch Data From a Remote Server - [x] 
My Calendar's API - [x] 
Multi-site Network Options - [x] 
Re-Generate Event Occurrences - Not included.
Drop MySQL Tables on Uninstall - [x] 

Docs: 
https://docs.joedolson.com/my-calendar/my-calendar-general-settings/
Added additional info for external API here: https://docs.joedolson.com/my-calendar/my-calendar-api/
Multi-site Network Options doc: https://docs.joedolson.com/my-calendar/category/settings/multisite/

2.b. My Calendar -> Settings -> Text
Calendar Text Settings - [x] 
Templated Text Fields - [x] 
Date and Time formats (working on improving)


Docs:
https://docs.joedolson.com/my-calendar/my-calendar-text-settings/

**Comment by joedolson** [comment]
It's been a long time, and a lot of updates to docs have happened since this was opened. I think it's too obsolete to be useful.
